### ISSUE TITLE
How to fetch component data

### ISSUE THREAD

**Issue by mclouvem** [combine/universal-react-redux#1]
Hi @calvinl!

First of all, thanks for your work in this starter kit. I'm getting started with react-redux  ecosystem and I would like to know where is the best place to retrieve component data. I saw that you are using isomorphic-fetch. Are you planning to release some kind of example (e.g todo app)? Or could you give me some advice how to retrieve data using your starter kit?

**Comment by calvinl** [comment]
@mclouvem Do you mean data coming from an external API? If so, you can use some middleware to do so. Check out [redux-api-middleware](https://github.com/agraboso/redux-api-middleware).

**Comment by calvinl** [comment]
Closing this issue, feel free to reopen it if I haven't answered your question!

**Comment by mclouvem** [comment]
@calvinl Yes, you partially answer my question, but I'm not sure how to get those data from external API on server-side.

Thanks for your support!

**Comment by calvinl** [comment]
You would retrieve from the API the same way, with an HTTP request.
