### ISSUE TITLE
Is it ok if I work toward a simpler webpack config ?

### ISSUE THREAD

**Issue by hartym** [combine/universal-react-redux#13]
I notice that the production webpack config is not working at all (using HMR, etc.).

Is it ok if I work toward a simpler configuration for webpack, keeping features the same for development?

The idea would be to
1. have a very readable configuration (as in python's «Explicit is better than implicit.»)
2. have the minimum duplication possible (plugin definitions, but more importantly configuration variables that for now are split between a lot of file, and that do not have a lot of meaning in their names)

**Comment by calvinl** [comment]
I'm definitely all in favor for a simpler webpack configuration! 1 and 2 on the list are excellent goals. I wanted to minimize duplication of plugin definition but I didn't do the best job at it. Feel free to have a crack at it.

HMR in production is definitely a no-no though. Why would you need that? HMR provides a great developer experience, and should be kept there only. See. https://github.com/gaearon/react-transform-hmr

What else isn't working in production?

**Comment by hartym** [comment]
I think I was not clear in my original message. Of course HMR is not for production, and in fact I really expressed myself badly. I did not talk about HMR but more like devserver and stuff, on my local host (as far as I remember), the prod webpack was looking some webpack dev server on :3001, which is what I wanted to say here.

Sorry for being not very understandable.

**Comment by hartym** [comment]
What do you think of this structure for webpack config ?

https://github.com/hartym/LeanJS/tree/master/config

**Comment by calvinl** [comment]
@hartym Apologies for misunderstanding! I'm definitely for improving the webpack configuration. Some of the things I wanted to do:
1. Convert the syntax to ES2015
2. Switch to (css-modules)[https://github.com/css-modules/css-modules](can be done later)
3. Reduce plugin duplication as you mentioned.

**Comment by calvinl** [comment]
Closing as of https://github.com/combine/react-redux-starter/tree/1.0.0
