### ISSUE TITLE
Reintegrate cordova support

### ISSUE THREAD

**Issue by jacobpdq** [combine/universal-react-redux#14]
Would be nice to have a develop-cordova  branch while it's being worked on as well. Thanks.

**Comment by calvinl** [comment]
if you need the old cordova support in the meantime, you can check out the previous tag: https://github.com/combine/react-redux-starter/tree/0.4.2

**Comment by jacobpdq** [comment]
Of course.

**Comment by jacobpdq** [comment]
I've also had to use webpack-sources to grab from common/assets just as an FYI.

`  new CopyWebpackPlugin([
            // {output}/file.txt 

```
        // Copy directory contents to {output}/ 
        { from: 'common/assets', to: 'dist/assets'}, 
    ], {
        ignore: [
            // Doesn't copy any files with a txt extension     
            '*.scss',
            'common/assets/stylesheets'
        ],
        // By default, we only copy modified files during 
        // a watch or webpack-dev-server build. Setting this 
        // to `true` copies all files. 
        copyUnmodified: true
```

  })`

**Comment by calvinl** [comment]
@subsumo See https://github.com/combine/react-redux-starter/pull/15

Please let me know how it goes for you.

**Comment by calvinl** [comment]
@subsumo I'm going to merge this in soon. Would appreciate a review beforehand to iron out any kinks. Thanks

**Comment by jacobpdq** [comment]
Awesome. @gzholdak and I will be giving it a test run today.

J
