### ISSUE TITLE
`if [ "$NODE_ENV" = "production" ]; then npm run build:production; fi`

### ISSUE THREAD

**Issue by Hazantip** [combine/universal-react-redux#17]
Can't do npm install. a have done all what you wrote at readme.md
### my system:
- windows 10 x64
- node 6.2.2
- npm latest

[npm-debug.txt](https://github.com/combine/react-redux-starter/files/328069/npm-debug.txt)

**Comment by calvinl** [comment]
@Hazantip: looks like it's not working for a windows system because the postinstall script is written as a linux shell script?

**Comment by Hazantip** [comment]
@calvinl  Thank you for quick anwer. Is there is a way how to fix it?

**Comment by calvinl** [comment]
@Hazantip: hard to say since i'm not on a windows system and i don't know windows command line scripting. You can alter this line: https://github.com/combine/react-redux-starter/blob/master/package.json#L28 to work on windows systems.

**Comment by Hazantip** [comment]
@calvinl  So bad(( your boilerplate looks very good for my project. Unfortunately i'm too don't know how to fix it(

**Comment by calvinl** [comment]
@Hazantip you can simply remove the `postinstall` line on package.json for now until i have a cross-OS solution for this. there's also some more information here:

https://github.com/use-init/init/issues/89
https://github.com/linnovate/mean/issues/43
