### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by Kimel1** [combine/universal-react-redux#26]
I deleted     `"postinstall": "if [ \"$NODE_ENV\" = \"production\" ]; then yarn run prod:build; fi" `from package.json and try to install but got an error.
[![Untitled.png](https://s3.postimg.org/8g2fwr037/Untitled.png)](https://postimg.org/image/akmsxu1pr/)

Your boilerplate is suit good for me, but this bug make me unhappy(

**Comment by calvinl** [comment]
@Kimel1 try this: https://github.com/npm/npm/issues/9204#issuecomment-216853959

`fsevents` is an optional dependency (for OSX). You shouldn't need it for Windows.

**Comment by Kimel1** [comment]
@calvinl 
[![Untitled.png](https://s16.postimg.org/xxo9z6g1x/Untitled.png)](https://postimg.org/image/cb99i5hhd/)

Still get errors(

**Comment by calvinl** [comment]
@Kimel1 Looks like the commands just weren't meant for Windows. I never built the boilerplate with Windows in mind. You should be able to edit the run commands in `package.json` to match Windows syntax and it should work (I believe). 

Unfortunately, I don't have a Windows machine to test on at this moment. I can take a look at it when I have time inside of a VM, but if you want to dig around and potentially submit a PR that would work for both Unix and Windows machines, please be my guest!

**Comment by Kimel1** [comment]
@calvinl 
You can use **better-npm-run** for cross-platform 
Look at similar boilerplate which has yarn integrated, but run on Windows/Linux w/o errors
https://github.com/davezuko/react-redux-starter-kit/blob/master/package.json

**Comment by calvinl** [comment]
@Kimel1 thanks, I will look into implementing this over the weekend.

**Comment by calvinl** [comment]
@Kimel1 Can you test this PR to see if it works for you? https://github.com/combine/universal-react-redux/pull/27
