### ISSUE TITLE
Import image from containers

### ISSUE THREAD

**Issue by xD3CODER** [combine/universal-react-redux#35]
I'm facing a problem with ISOtools and babel.
I can't import or require an image from the common folder
The output when server is starting is 
```
/var/www/react/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /var/www/react/common/images/favicon.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 |
  3 |
[nodemon] app crashed - waiting for file changes before starting...

```

My image is correctly intepreted by webpack because it's present in the webpack-assets.json

Any idea ?

**Comment by calvinl** [comment]
Hi! I’ve actually come across this issue too. It seems to work properly if you use `require` rather than `import` for the image. Not sure why yet, but it’s a workaround for now!

**Comment by xD3CODER** [comment]
Really ? I've got the same issue with ``import``

**Comment by calvinl** [comment]
Can you try using require inside your react component like inside the render method?

**Comment by xD3CODER** [comment]
I tried, and exactly the same issue

**Comment by xD3CODER** [comment]
My bad! It's working with this method

**Comment by calvinl** [comment]
Great! If you ever figure out a solution to use with import, please put up a PR. Going to close this ticket.
