### ISSUE TITLE
Why copy server path into dist folder ?

### ISSUE THREAD

**Issue by xD3CODER** [combine/universal-react-redux#39]
I noticed that the command `prod:build:server` copy server folder into public dist folder.
Server side code is therefore served by express in HTTP.
Is it wanted or is it a mistake ?

![image](https://user-images.githubusercontent.com/14862690/33790370-9b64393e-dc77-11e7-9456-fccbd3773a10.png)
I suggest to build public files into `dist/public` and serve this directory with express rather than entiere dist directory

**Comment by calvinl** [comment]
I’m not in front of a computer right now, but is `dist` served as static? If so, that’s a mistake. Open to a PR if so, good catch!

**Comment by xD3CODER** [comment]
Fixed in #38
