### ISSUE TITLE
CSS base/_style not counted as part of style

### ISSUE THREAD

**Issue by xD3CODER** [combine/universal-react-redux#41]
Hi,

I'm unable to configure webpack to build the .scss files from the path `common/css/base` and manage them as hot reload

Any idea ?

**Comment by calvinl** [comment]
@xD3VHAX is this in the latest version?

**Comment by calvinl** [comment]
I think [this line](https://github.com/combine/universal-react-redux/blob/master/webpack/base.js#L100) needs to have `css-hot-loader` added to it, if you're referring to latest version.

**Comment by xD3CODER** [comment]
@calvinl Yes in the last one.
My objective is to build the folder inside app.css file both dev and prod

**Comment by calvinl** [comment]
@xD3VHAX should be fixed in `6.0.1`. Can you confirm?

**Comment by xD3CODER** [comment]
@calvinl Yes it works fine, I don't know why it didn't work on my fork, thanks !
