### ISSUE TITLE
react-loadable.json not found

### ISSUE THREAD

**Issue by NandoSangenetto** [combine/universal-react-redux#48]
I installed the project and when I run `npm run prod:build` I received this error:
```Module not found: Error: Can't resolve '../../react-loadable.json'```

This file does not exists and only is created after the build, which fails.

**Comment by calvinl** [comment]
@nandosangenetto thanks for catching that. i'll push out a fix for that soon.

**Comment by calvinl** [comment]
In the meantime, if you comment out [this line](https://github.com/combine/universal-react-redux/blob/master/server/renderer/handler.js#L18), it should work.

**Comment by calvinl** [comment]
@nandosangenetto Fixed in latest `master`, thanks again for the report.
