### ISSUE TITLE
[Question] Pre fetch data before react renders

### ISSUE THREAD

**Issue by vianhanif** [combine/universal-react-redux#53]
Similarly, this is a feature that Next.js has provided with **getInitialProps** function (if you might already know, it basically giving us the possibility to run redux actions to prefetch data from backend, so the component will already has data to render with).  Has anyone tried it ? any help would be great because Next.js is the last thing I want to use for my work. Thanks~

**Comment by calvinl** [comment]
@vianhanif This is also a feature in this boilerplate. You can use a static `fetchData` method on your component to pre-fetch on the server side. See https://github.com/combine/universal-react-redux#pre-fetching-data-for-server-side-rendering-ssr

Closing for now. Feel free to reopen if I've misinterpreted your question.

**Comment by vianhanif** [comment]
ooh hha, you're right... stupid me. sorry for the hassle. Thanks 😄

**Comment by vianhanif** [comment]
@calvinl what other objects available from **fetchData** other than the **store** object?

**Comment by calvinl** [comment]
See here: https://github.com/combine/universal-react-redux/blob/master/server/renderer/handler.js#L116

fetchData is called with an object that includes: `{ store, route, match }`, where `match` is the object returned by `react-router`'s [matchPath](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/matchPath.md)
